export const usersSeedData = [
  { ci: '85010112345', firstName: 'Carlos', lastName: 'García', email: 'carlos.garcia@example.com', password: 'Password123!', address: 'Calle 23 #456, Vedado, La Habana' },
  { ci: '90050298765', firstName: 'María', lastName: 'Rodríguez', email: 'maria.rodriguez@example.com', password: 'Password123!', address: 'Avenida 5ta #789, Miramar, La Habana' },
  { ci: '88121534567', firstName: 'José', lastName: 'Fernández', email: 'jose.fernandez@example.com', password: 'Password123!', address: 'Calle Real #123, Trinidad, Sancti Spíritus' },
  { ci: '92030445678', firstName: 'Ana', lastName: 'Martínez', email: 'ana.martinez@example.com', password: 'Password123!', address: 'Calle Maceo #234, Varadero, Matanzas' },
  { ci: '87090656789', firstName: 'Luis', lastName: 'López', email: 'luis.lopez@example.com', password: 'Password123!', address: 'Parque Céspedes #345, Santiago de Cuba' },
  { ci: '91020767890', firstName: 'Carmen', lastName: 'Pérez', email: 'carmen.perez@example.com', password: 'Password123!', address: 'Calle Independencia #456, Cienfuegos' },
  { ci: '89110878901', firstName: 'Pedro', lastName: 'González', email: 'pedro.gonzalez@example.com', password: 'Password123!', address: 'Calle Martí #567, Camagüey' },
  { ci: '93050989012', firstName: 'Laura', lastName: 'Sánchez', email: 'laura.sanchez@example.com', password: 'Password123!', address: 'Avenida de los Presidentes #678, La Habana' },
  { ci: '86081090123', firstName: 'Roberto', lastName: 'Díaz', email: 'roberto.diaz@example.com', password: 'Password123!', address: 'Calle Obispo #789, Habana Vieja, La Habana' },
  { ci: '94040101234', firstName: 'Isabel', lastName: 'Torres', email: 'isabel.torres@example.com', password: 'Password123!', address: 'Calle Santa Clara #890, Villa Clara' },
  { ci: '85051212456', firstName: 'Jorge', lastName: 'Ramírez', email: 'jorge.ramirez@example.com', password: 'Password123!', address: 'Calle 10 #234, Holguín' },
  { ci: '91060323567', firstName: 'Claudia', lastName: 'Hernández', email: 'claudia.hernandez@example.com', password: 'Password123!', address: 'Avenida Libertad #456, Pinar del Río' },
  { ci: '88070434678', firstName: 'Miguel', lastName: 'Castro', email: 'miguel.castro@example.com', password: 'Password123!', address: 'Calle Central #567, Bayamo, Granma' },
  { ci: '93081545789', firstName: 'Silvia', lastName: 'Morales', email: 'silvia.morales@example.com', password: 'Password123!', address: 'Paseo Martí #678, Ciego de Ávila' },
  { ci: '86091656890', firstName: 'Raúl', lastName: 'Vargas', email: 'raul.vargas@example.com', password: 'Password123!', address: 'Calle Aguilera #789, Las Tunas' },
  { ci: '92101767901', firstName: 'Elena', lastName: 'Ruiz', email: 'elena.ruiz@example.com', password: 'Password123!', address: 'Avenida de la Paz #890, Guantánamo' },
  { ci: '89111878012', firstName: 'Fernando', lastName: 'Jiménez', email: 'fernando.jimenez@example.com', password: 'Password123!', address: 'Calle Principal #901, Artemisa' },
  { ci: '94121989123', firstName: 'Beatriz', lastName: 'Ortiz', email: 'beatriz.ortiz@example.com', password: 'Password123!', address: 'Calle Mayor #123, Mayabeque' },
  { ci: '85020190234', firstName: 'Alberto', lastName: 'Méndez', email: 'alberto.mendez@example.com', password: 'Password123!', address: 'Avenida Central #234, Isla de la Juventud' },
  { ci: '90030201345', firstName: 'Patricia', lastName: 'Vega', email: 'patricia.vega@example.com', password: 'Password123!', address: 'Calle 1ra #345, Sancti Spíritus' },
  { ci: '88040312456', firstName: 'Ricardo', lastName: 'Reyes', email: 'ricardo.reyes@example.com', password: 'Password123!', address: 'Parque Central #456, Matanzas' },
  { ci: '92050423567', firstName: 'Adriana', lastName: 'Silva', email: 'adriana.silva@example.com', password: 'Password123!', address: 'Calle Colón #567, Cienfuegos' },
  { ci: '87060534678', firstName: 'Ernesto', lastName: 'Campos', email: 'ernesto.campos@example.com', password: 'Password123!', address: 'Avenida Maceo #678, Villa Clara' },
  { ci: '91070645789', firstName: 'Mónica', lastName: 'Ramos', email: 'monica.ramos@example.com', password: 'Password123!', address: 'Calle del Sol #789, Camagüey' },
  { ci: '89080756890', firstName: 'Daniel', lastName: 'Cortés', email: 'daniel.cortes@example.com', password: 'Password123!', address: 'Paseo Marítimo #890, Santiago de Cuba' },
  { ci: '93090867901', firstName: 'Valentina', lastName: 'Navarro', email: 'valentina.navarro@example.com', password: 'Password123!', address: 'Calle Enramadas #901, Santiago de Cuba' },
  { ci: '86100978012', firstName: 'Héctor', lastName: 'Luna', email: 'hector.luna@example.com', password: 'Password123!', address: 'Avenida Lenin #234, Holguín' },
  { ci: '94111089123', firstName: 'Gabriela', lastName: 'Flores', email: 'gabriela.flores@example.com', password: 'Password123!', address: 'Calle Frexes #345, Holguín' },
  { ci: '85121190234', firstName: 'Andrés', lastName: 'Medina', email: 'andres.medina@example.com', password: 'Password123!', address: 'Calle Martí #456, Pinar del Río' },
  { ci: '90010201345', firstName: 'Cristina', lastName: 'Paredes', email: 'cristina.paredes@example.com', password: 'Password123!', address: 'Avenida Principal #567, Granma' },
  { ci: '88020312456', firstName: 'Francisco', lastName: 'Cabrera', email: 'francisco.cabrera@example.com', password: 'Password123!', address: 'Calle 23 #678, Ciego de Ávila' },
  { ci: '92030423567', firstName: 'Natalia', lastName: 'Rojas', email: 'natalia.rojas@example.com', password: 'Password123!', address: 'Parque Agramonte #789, Las Tunas' },
  { ci: '87040534678', firstName: 'Guillermo', lastName: 'Soto', email: 'guillermo.soto@example.com', password: 'Password123!', address: 'Calle Calixto García #890, Guantánamo' },
  { ci: '91050645789', firstName: 'Alejandra', lastName: 'Bravo', email: 'alejandra.bravo@example.com', password: 'Password123!', address: 'Avenida 26 #123, Artemisa' },
  { ci: '89060756890', firstName: 'Sergio', lastName: 'Ponce', email: 'sergio.ponce@example.com', password: 'Password123!', address: 'Calle 41 #234, Mayabeque' },
  { ci: '93070867901', firstName: 'Diana', lastName: 'Guzmán', email: 'diana.guzman@example.com', password: 'Password123!', address: 'Calle 39 #345, La Habana' },
  { ci: '86080978012', firstName: 'Tomás', lastName: 'Acosta', email: 'tomas.acosta@example.com', password: 'Password123!', address: 'Calle L #456, Vedado, La Habana' },
  { ci: '94091089123', firstName: 'Carolina', lastName: 'Delgado', email: 'carolina.delgado@example.com', password: 'Password123!', address: 'Avenida 3ra #567, Miramar, La Habana' },
  { ci: '85101190234', firstName: 'Óscar', lastName: 'Quintana', email: 'oscar.quintana@example.com', password: 'Password123!', address: 'Calle O #678, Vedado, La Habana' },
  { ci: '90111201345', firstName: 'Lucía', lastName: 'Ibarra', email: 'lucia.ibarra@example.com', password: 'Password123!', address: 'Malecón #789, Centro Habana' },
  { ci: '88121312456', firstName: 'Manuel', lastName: 'Serrano', email: 'manuel.serrano@example.com', password: 'Password123!', address: 'Calle Neptuno #890, Centro Habana' },
  { ci: '92010423567', firstName: 'Victoria', lastName: 'Lara', email: 'victoria.lara@example.com', password: 'Password123!', address: 'Calle San Rafael #901, Centro Habana' },
  { ci: '87020534678', firstName: 'Ignacio', lastName: 'Mendoza', email: 'ignacio.mendoza@example.com', password: 'Password123!', address: 'Avenida Paseo #123, Vedado, La Habana' },
  { ci: '91030645789', firstName: 'Mariana', lastName: 'Estrada', email: 'mariana.estrada@example.com', password: 'Password123!', address: 'Calle 21 #234, Vedado, La Habana' },
  { ci: '89040756890', firstName: 'Vicente', lastName: 'Salazar', email: 'vicente.salazar@example.com', password: 'Password123!', address: 'Calle G #345, Vedado, La Habana' },
  { ci: '93050867901', firstName: 'Sofía', lastName: 'Romero', email: 'sofia.romero@example.com', password: 'Password123!', address: 'Calle 23 #456, El Vedado, La Habana' },
  { ci: '86060978012', firstName: 'Julio', lastName: 'Aguilar', email: 'julio.aguilar@example.com', password: 'Password123!', address: 'Línea #567, Vedado, La Habana' },
  { ci: '94071089123', firstName: 'Camila', lastName: 'Carrillo', email: 'camila.carrillo@example.com', password: 'Password123!', address: 'Calle N #678, Vedado, La Habana' },
  { ci: '85081190234', firstName: 'Emilio', lastName: 'Castillo', email: 'emilio.castillo@example.com', password: 'Password123!', address: 'Calle 15 #789, Vedado, La Habana' },
  { ci: '90091201345', firstName: 'Valeria', lastName: 'Mora', email: 'valeria.mora@example.com', password: 'Password123!', address: 'Calle M #890, Vedado, La Habana' },
];
