export const casasSeedData = [
  // La Habana - 10 casas
  { userEmail: 'carlos.garcia@example.com', title: 'Casa Colonial en Vedado', description: 'Hermosa casa colonial de los años 40 con patio interior y terraza. Ubicada en el corazón del Vedado, cerca de la Universidad de La Habana.', pricePerNight: 3500, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Calle 17 #254 entre H e I, Vedado, La Habana', municipalityId: 7, contacts: [{ name: 'Carlos García', number: '53012345' }] },
  { userEmail: 'maria.rodriguez@example.com', title: 'Apartamento Moderno en Miramar', description: 'Apartamento de lujo completamente equipado con vista al mar. A/C en todas las habitaciones, WiFi, y estacionamiento privado.', pricePerNight: 5000, bedroomsCount: 2, bathroomsCount: 2, capacityPeople: 4, address: 'Avenida 5ta #6802 entre 68 y 70, Miramar, Playa', municipalityId: 5, contacts: [{ name: 'María Rodríguez', number: '53098765' }] },
  { userEmail: 'laura.sanchez@example.com', title: 'Penthouse en El Vedado', description: 'Penthouse de lujo con terraza privada y vista 360° de La Habana. Completamente amueblado con estilo moderno.', pricePerNight: 6500, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Calle L #456 esquina a 23, Vedado, La Habana', municipalityId: 7, contacts: [{ name: 'Laura Sánchez', number: '53089012' }] },
  { userEmail: 'roberto.diaz@example.com', title: 'Casa Colonial Habana Vieja', description: 'Casa restaurada del siglo XVIII en pleno corazón de Habana Vieja. Balcón con vista a la calle.', pricePerNight: 4000, bedroomsCount: 2, bathroomsCount: 2, capacityPeople: 4, address: 'Calle Mercaderes #315, Habana Vieja', municipalityId: 2, contacts: [{ name: 'Roberto Díaz', number: '53090123' }] },
  { userEmail: 'tomas.acosta@example.com', title: 'Estudio en Nuevo Vedado', description: 'Estudio acogedor perfecto para parejas. WiFi de alta velocidad, cocina equipada, muy tranquilo.', pricePerNight: 1800, bedroomsCount: 1, bathroomsCount: 1, capacityPeople: 2, address: 'Calle 26 #112 entre 19 y 21, Nuevo Vedado', municipalityId: 7, contacts: [{ name: 'Tomás Acosta', number: '53001111' }] },
  { userEmail: 'lucia.ibarra@example.com', title: 'Casa con Piscina en Playa', description: 'Casa espaciosa con piscina y jardín tropical. Ideal para eventos y reuniones familiares.', pricePerNight: 7000, bedroomsCount: 5, bathroomsCount: 4, capacityPeople: 10, address: 'Calle 70 #503 entre 5ta y 7ma, Playa', municipalityId: 5, contacts: [{ name: 'Lucía Ibarra', number: '53002222' }] },
  { userEmail: 'manuel.serrano@example.com', title: 'Apartamento Centro Habana', description: 'Apartamento céntrico cerca del Capitolio. Ideal para explorar La Habana Vieja.', pricePerNight: 2500, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle Neptuno #456', municipalityId: 3, contacts: [{ name: 'Manuel Serrano', number: '53003333' }] },
  { userEmail: 'victoria.lara@example.com', title: 'Loft en Centro Habana', description: 'Loft moderno con decoración vintage. WiFi rápido y aire acondicionado.', pricePerNight: 3200, bedroomsCount: 1, bathroomsCount: 1, capacityPeople: 2, address: 'Calle San Rafael #234', municipalityId: 3, contacts: [{ name: 'Victoria Lara', number: '53004444' }] },
  { userEmail: 'ignacio.mendoza@example.com', title: 'Casa Familiar en Vedado', description: 'Casa amplia ideal para familias. Jardín, garaje y cocina completa.', pricePerNight: 4500, bedroomsCount: 4, bathroomsCount: 3, capacityPeople: 8, address: 'Avenida Paseo #789', municipalityId: 7, contacts: [{ name: 'Ignacio Mendoza', number: '53005555' }] },
  { userEmail: 'mariana.estrada@example.com', title: 'Apartamento Vista al Mar', description: 'Apartamento con hermosa vista al Malecón habanero. Moderno y equipado.', pricePerNight: 5500, bedroomsCount: 2, bathroomsCount: 2, capacityPeople: 4, address: 'Malecón #567', municipalityId: 7, contacts: [{ name: 'Mariana Estrada', number: '53006666' }] },
  
  // Matanzas - 3 casas
  { userEmail: 'ana.martinez@example.com', title: 'Villa Frente al Mar en Varadero', description: 'Villa moderna con acceso directo a la playa. Piscina privada, jardín, BBQ. Ideal para familias.', pricePerNight: 8000, bedroomsCount: 4, bathroomsCount: 3, capacityPeople: 8, address: 'Avenida 1ra y Calle 58, Varadero', municipalityId: 25, contacts: [{ name: 'Ana Martínez', number: '53045678' }] },
  { userEmail: 'ricardo.reyes@example.com', title: 'Casa en Varadero Centro', description: 'Casa confortable a 2 cuadras de la playa. Desayuno incluido.', pricePerNight: 4500, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Calle 42 #234, Varadero', municipalityId: 25, contacts: [{ name: 'Ricardo Reyes', number: '53007777' }] },
  { userEmail: 'patricia.vega@example.com', title: 'Apartamento Playa Matanzas', description: 'Apartamento frente al mar con todas las comodidades.', pricePerNight: 3800, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Paseo Marítimo #123, Matanzas', municipalityId: 17, contacts: [{ name: 'Patricia Vega', number: '53008888' }] },
  
  // Sancti Spíritus - 2 casas
  { userEmail: 'jose.fernandez@example.com', title: 'Casa Particular en Trinidad', description: 'Casa colonial en el centro histórico de Trinidad, declarado Patrimonio de la Humanidad. Desayuno incluido.', pricePerNight: 2500, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle Simón Bolívar #283, Trinidad', municipalityId: 130, contacts: [{ name: 'José Fernández', number: '53134567' }] },
  { userEmail: 'silvia.morales@example.com', title: 'Casa Colonial Trinidad', description: 'Hermosa casa con patio central y fuente. Ambiente colonial auténtico.', pricePerNight: 3000, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Calle Real del Jigüe #156, Trinidad', municipalityId: 130, contacts: [{ name: 'Silvia Morales', number: '53009999' }] },
  
  // Santiago de Cuba - 3 casas
  { userEmail: 'luis.lopez@example.com', title: 'Casa Vista Santiago', description: 'Casa amplia con vista panorámica de Santiago de Cuba. Terraza espaciosa, cocina equipada, parqueo disponible.', pricePerNight: 3000, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Calle 3 #152, Vista Alegre, Santiago de Cuba', municipalityId: 147, contacts: [{ name: 'Luis López', number: '53056789' }] },
  { userEmail: 'daniel.cortes@example.com', title: 'Apartamento Centro Santiago', description: 'Apartamento céntrico cerca del Parque Céspedes. Muy bien ubicado.', pricePerNight: 2800, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle Heredia #234', municipalityId: 147, contacts: [{ name: 'Daniel Cortés', number: '53010101' }] },
  { userEmail: 'valentina.navarro@example.com', title: 'Casa en Santiago Centro', description: 'Casa tradicional santiaguera con patio y portal. Muy acogedora.', pricePerNight: 2200, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle Enramadas #345', municipalityId: 147, contacts: [{ name: 'Valentina Navarro', number: '53011111' }] },
  
  // Cienfuegos - 2 casas
  { userEmail: 'carmen.perez@example.com', title: 'Apartamento Centro Cienfuegos', description: 'Apartamento céntrico en la Perla del Sur. A pasos del Parque José Martí y el Malecón.', pricePerNight: 2800, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Avenida 54 #2910 entre 29 y 31, Cienfuegos', municipalityId: 48, contacts: [{ name: 'Carmen Pérez', number: '53067890' }] },
  { userEmail: 'adriana.silva@example.com', title: 'Casa Punta Gorda', description: 'Casa elegante en el barrio de Punta Gorda con vista a la bahía.', pricePerNight: 4200, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Calle 37 #456, Punta Gorda', municipalityId: 48, contacts: [{ name: 'Adriana Silva', number: '53012121' }] },
  
  // Villa Clara - 3 casas
  { userEmail: 'isabel.torres@example.com', title: 'Casa de Campo en Villa Clara', description: 'Casa campestre rodeada de naturaleza. Perfecta para desconectar. Piscina natural, huerto orgánico.', pricePerNight: 2000, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Carretera a Caibarién Km 3.5, Villa Clara', municipalityId: 118, contacts: [{ name: 'Isabel Torres', number: '53001234' }] },
  { userEmail: 'ernesto.campos@example.com', title: 'Apartamento Santa Clara', description: 'Apartamento moderno en el centro de Santa Clara. WiFi incluido.', pricePerNight: 2500, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle Independencia #234', municipalityId: 118, contacts: [{ name: 'Ernesto Campos', number: '53013131' }] },
  { userEmail: 'sofia.romero@example.com', title: 'Casa Colonial Santa Clara', description: 'Casa colonial cerca del Parque Vidal. Habitaciones amplias.', pricePerNight: 3200, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Calle Colón #345', municipalityId: 118, contacts: [{ name: 'Sofía Romero', number: '53014141' }] },
  
  // Camagüey - 2 casas
  { userEmail: 'pedro.gonzalez@example.com', title: 'Casa Camagüeyana Tradicional', description: 'Casa típica camagüeyana con tinajones en el patio. Ambiente familiar y acogedor.', pricePerNight: 2200, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle República #56, Camagüey', municipalityId: 89, contacts: [{ name: 'Pedro González', number: '53078901' }] },
  { userEmail: 'monica.ramos@example.com', title: 'Casa Centro Camagüey', description: 'Casa en pleno centro histórico. Arquitectura colonial única.', pricePerNight: 2800, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Calle Maceo #234', municipalityId: 89, contacts: [{ name: 'Mónica Ramos', number: '53015151' }] },
  
  // Holguín - 2 casas
  { userEmail: 'jorge.ramirez@example.com', title: 'Casa en Holguín Centro', description: 'Casa confortable en el centro de Holguín. Cerca de todo.', pricePerNight: 2400, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle Libertad #123', municipalityId: 68, contacts: [{ name: 'Jorge Ramírez', number: '53016161' }] },
  { userEmail: 'hector.luna@example.com', title: 'Apartamento Holguín', description: 'Apartamento moderno con todas las comodidades.', pricePerNight: 2600, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Avenida Lenin #456', municipalityId: 68, contacts: [{ name: 'Héctor Luna', number: '53017171' }] },
  
  // Pinar del Río - 2 casas
  { userEmail: 'claudia.hernandez@example.com', title: 'Casa en Viñales', description: 'Casa en el valle de Viñales con vista a los mogotes. Perfecta para ecoturismo.', pricePerNight: 3500, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Carretera a Viñales Km 2', municipalityId: 35, contacts: [{ name: 'Claudia Hernández', number: '53018181' }] },
  { userEmail: 'andres.medina@example.com', title: 'Casa Pinar Centro', description: 'Casa céntrica en Pinar del Río. Ambiente tranquilo.', pricePerNight: 2000, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle Martí #234', municipalityId: 33, contacts: [{ name: 'Andrés Medina', number: '53019191' }] },
  
  // Granma - 2 casas
  { userEmail: 'miguel.castro@example.com', title: 'Casa en Bayamo', description: 'Casa colonial en Bayamo, cuna de la nacionalidad cubana.', pricePerNight: 2200, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle General García #123', municipalityId: 60, contacts: [{ name: 'Miguel Castro', number: '53020202' }] },
  { userEmail: 'cristina.paredes@example.com', title: 'Casa Familiar Bayamo', description: 'Casa espaciosa ideal para grupos. Patio amplio.', pricePerNight: 2800, bedroomsCount: 4, bathroomsCount: 2, capacityPeople: 8, address: 'Calle Maceo #234', municipalityId: 60, contacts: [{ name: 'Cristina Paredes', number: '53021212' }] },
  
  // Ciego de Ávila - 1 casa
  { userEmail: 'francisco.cabrera@example.com', title: 'Casa en Ciego de Ávila', description: 'Casa confortable en el corazón de Cuba. Muy tranquila.', pricePerNight: 2100, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle Independencia #345', municipalityId: 95, contacts: [{ name: 'Francisco Cabrera', number: '53022222' }] },
  
  // Las Tunas - 1 casa
  { userEmail: 'raul.vargas@example.com', title: 'Casa Las Tunas', description: 'Casa acogedora en la ciudad escultura de Cuba.', pricePerNight: 1900, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Avenida Camilo Cienfuegos #234', municipalityId: 107, contacts: [{ name: 'Raúl Vargas', number: '53023232' }] },
  
  // Guantánamo - 1 casa
  { userEmail: 'elena.ruiz@example.com', title: 'Casa en Guantánamo', description: 'Casa tradicional en Guantánamo. Hospitalidad garantizada.', pricePerNight: 1800, bedroomsCount: 2, bathroomsCount: 1, capacityPeople: 4, address: 'Calle Pedro A. Pérez #123', municipalityId: 157, contacts: [{ name: 'Elena Ruiz', number: '53024242' }] },
  
  // Artemisa - 1 casa
  { userEmail: 'fernando.jimenez@example.com', title: 'Casa en Artemisa', description: 'Casa moderna en Artemisa. Cerca de La Habana.', pricePerNight: 2300, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Calle 28 #234', municipalityId: 165, contacts: [{ name: 'Fernando Jiménez', number: '53025252' }] },
  
  // Mayabeque - 1 casa
  { userEmail: 'beatriz.ortiz@example.com', title: 'Casa en San José de las Lajas', description: 'Casa familiar en Mayabeque. Jardín amplio.', pricePerNight: 2000, bedroomsCount: 3, bathroomsCount: 2, capacityPeople: 6, address: 'Avenida 47 #345', municipalityId: 154, contacts: [{ name: 'Beatriz Ortiz', number: '53026262' }] },
];
